name: build

on:
  push:
  workflow_dispatch:
    inputs:
      build:
        description: "Build otfccpp branch"
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2

    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    
    # - run: sudo apt update && sudo apt install make -y

    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        mkdir nextflow
        cd nextflow
        curl -fsSL https://get.nextflow.io | bash
        export PATH=$PATH:$PWD
        
    - name: Building
      run: |
        podman run -it --rm -v $PWD:/mnt -v /mnt -e XMAKE_ROOT=y alpine
        apk add bash xmake gcc g++ xz
        package/linux-amd64.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        name: build
        path: build/**

    




  
        
